# Disables subtitle rendering in thumbnails to reduce CPU load.
mpv_no_sub=yes

# Reduces the number of thumbnails generated for local files to 100.
thumbnail_count=100

# Reduces the number of thumbnails for network streams to 40.
remote_thumbnail_count=40
